{{with .Values -}}
---
###
### Web RBAC
###
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-web
  namespace: {{.Namespace}}
  labels:
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: ["linkerd-config"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-web
  namespace: {{.Namespace}}
  labels:
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
roleRef:
  kind: Role
  name: linkerd-web
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.Namespace}}
---
{{- if not .RestrictDashboardPrivileges }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Namespace}}-web-admin
  labels:
    {{.ControllerComponentLabel}}: web
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-{{.Namespace}}-tap-admin
subjects:
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.Namespace}}
---
{{- end}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: web
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
{{- end }}
